# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
vec_n=np.zeros(10)
print(vec_n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [16]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [17]:
arr.shape

(40,)

5. Print the type of the previous array in question 3

In [19]:
arr.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [21]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/javer/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/javer/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/javer/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [24]:
arr.shape

(40,)

8. Create a boolean array with all the True values

In [25]:
np.full(10,1,bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [27]:
np.arange(3*3).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Create a three dimensional array



In [28]:
np.arange(3*3*2).reshape(3,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [29]:
arr=np.arange(10,20)
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [31]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [36]:
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [37]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [41]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [43]:
#find maximum in pair
def minn(x, y):
    """Get the minimum of two items"""
    if x <= y:
        return x
    else:
        return y

pair_min = np.vectorize(minn, otypes=[int])
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])

pair_min(arr1, arr2)

array([[0, 2, 1],
       [4, 2, 6]])

17. Extract all odd numbers from arr with values(0-9)

In [45]:
a=np.arange(0,10)
a[a%2!=0]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [47]:
a[a%2!=0]=-1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [50]:
arr = np.arange(10)
arr[5:9]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [52]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [54]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[arr2d==5]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]=64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [59]:
arr2d=np.arange(2*5).reshape(2,5)
print(arr2d[0,0:])

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [62]:
arr2d=np.arange(2*5).reshape(2,5)
print(arr2d)
print("2nd value in 2nd row is ",arr2d[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
2nd value in 2nd row is  6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [65]:
arr2d=np.arange(2*5).reshape(2,5)
print(arr2d)
print(arr2d[0:2,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [74]:
arr2d=np.random.uniform(0,100, size=(10,10))
print(arr2d)
print("Minimum value is " ,arr2d.min())
print("Maximum value is " ,arr2d.max())


[[1.81916174e+00 6.78650961e+01 1.90584101e+01 6.04545388e+01
  6.64046775e+01 4.46507522e+01 3.14214927e+01 6.42274830e+01
  6.10964461e+01 3.32994975e+01]
 [4.91706290e+01 8.48190081e+01 3.73374013e+01 7.14241388e+01
  8.27762254e+01 7.08387179e-02 2.53931027e+01 3.59226034e+01
  7.00397248e+01 4.09656030e+01]
 [9.78570009e+01 5.12776924e+01 1.69888804e+01 4.42507433e+01
  7.15056403e+01 4.15805657e+00 9.39388987e+01 9.41024399e+01
  6.29025009e+01 5.10143676e+01]
 [6.11459099e+01 9.00545429e+01 8.76083036e+01 4.92953443e+01
  5.97842144e+01 6.64609773e+01 8.22270855e+01 4.23424227e+01
  1.56242774e+01 1.08518727e+01]
 [6.89948034e+00 6.63984397e+01 6.73252151e+01 4.91136255e+01
  4.11609455e+01 7.67723904e+01 4.00057710e+01 9.02124671e+01
  6.33480370e+01 7.13371312e+01]
 [7.49412026e+01 2.00584637e+01 7.63352786e+01 7.02051179e+01
  9.46582329e+01 7.44683263e+00 4.12699772e+01 9.30769330e+01
  3.71693593e+01 8.82144574e+01]
 [9.18730213e+01 1.08502966e+01 1.03050627e+01 8.80502683e

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [75]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [76]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [80]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!="Will"]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.52773105  0.63981086  0.86869861  1.42961573]
 [ 2.2039423  -0.47338927  0.52394563  0.36412831]
 [ 1.56867237  0.478685   -0.05517824  0.02885095]
 [ 0.40908604 -0.26431142 -0.17909113 -1.33667243]
 [-0.21952394  1.5299072  -0.99569117 -1.01956107]
 [ 0.51045096  0.83162001  0.41050718 -0.4680174 ]
 [-0.53589655  0.42374921 -1.19669977  0.14033296]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
a=data[names!="Will"]
b=data[names=="Joe"]
print(np.setdiff1d(a,b).reshape(2,4))

[[-1.35851432 -0.89099414 -0.77131475 -0.63378949]
 [-0.2646954  -0.1355331   0.12484682  0.65423843]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [96]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[11.87198814 14.37422285 14.96041866]
 [ 5.27956315  6.75444058  8.68568271]
 [ 8.27975343  3.81720169  2.86889312]
 [ 1.30815561  4.14347798 14.15193634]
 [ 2.57073748  5.20968374  3.64162998]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [97]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr)

[[[10.20796588  5.98179016  8.48941256  4.39669587]
  [ 6.90011046  6.29201083  2.32020904  5.70144368]]

 [[14.37634069  9.60319005 11.24220278  8.97870817]
  [ 3.54646185 14.1449748  10.82929372  3.16853016]]]


33. Swap axes of the array you created in Question 32

In [99]:
np.swapaxes(rand_arr,0,2)

array([[[10.20796588, 14.37634069],
        [ 6.90011046,  3.54646185]],

       [[ 5.98179016,  9.60319005],
        [ 6.29201083, 14.1449748 ]],

       [[ 8.48941256, 11.24220278],
        [ 2.32020904, 10.82929372]],

       [[ 4.39669587,  8.97870817],
        [ 5.70144368,  3.16853016]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [106]:
arr=np.arange(4,15)
y = np.sqrt(np.abs(arr))
print(arr)
print(y)

[ 4  5  6  7  8  9 10 11 12 13 14]
[2.         2.23606798 2.44948974 2.64575131 2.82842712 3.
 3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [110]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5,8,5,3,8,2])
b = np.array([6, 3, 4, 8, 9, 7, 1,1,8,4,9,3])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5, 8, 8, 4, 9, 3])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [111]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [112]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [116]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])
sampleArray[1,0:]=newColumn[0:]
print(sampleArray)

[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [120]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
x.dot(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [124]:
rma = np.random.rand(5,4)
print(rma)
rma.sum()

[[0.03957742 0.32134042 0.45197088 0.16556763]
 [0.12738593 0.7407635  0.39690433 0.00140663]
 [0.40427888 0.92313932 0.98300772 0.5409413 ]
 [0.48488617 0.75095567 0.42876559 0.873716  ]
 [0.07675881 0.64372146 0.1598567  0.37527578]]


8.890220158119813